# Generated by Django 5.2.1 on 2025-05-26 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0005_alter_women_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="women",
            name="user",
        ),
    ]
